# 🎙️ Antislash Talk Monorepo Workspace
# Modern monorepo structure with pnpm workspaces

packages:
  # Main web application
  - 'apps/web'
  
  # Backend services
  - 'apps/api'
  
  # Supabase self-hosted configuration
  - 'packages/supabase'
  
  # Shared libraries
  - 'packages/shared'
  - 'packages/ui'
  - 'packages/types'
  
  # Development tools
  - 'packages/config'
  - 'packages/scripts'
  
  # Documentation
  - 'apps/docs'

