// Database types - Auto-generated by Supabase
// Run: pnpm db:types to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      meetings: {
        Row: {
          id: string
          title: string
          description: string | null
          audio_url: string | null
          transcript: string | null
          summary: string | null
          provider: string
          status: string
          created_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          audio_url?: string | null
          transcript?: string | null
          summary?: string | null
          provider: string
          status?: string
          created_at?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          audio_url?: string | null
          transcript?: string | null
          summary?: string | null
          provider?: string
          status?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}

